{
 "title": "Client-data",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "prefix",
    "query": "SELECT SUBSTRING_INDEX(table_name, 'users', 1) \nFROM information_schema.tables \nWHERE table_schema = DATABASE() \nAND table_name LIKE '%users' \nORDER BY LENGTH(table_name) ASC \nLIMIT 1;"
   }
  ]
 },
 "panels": [
  {
   "title": "Tiempo de Actividad",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "Zabbix server" },
     "item": { "filter": "System uptime" },
     "itemTag": { "filter": "component: system" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Potencia Disponible del servidor",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "bit-rds-mysql" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Última copia de seguridad",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "wordpress",
     "rawSql": "SELECT\r\n  -- Intentamos extraer los primeros 10 números que parezcan una fecha (Timestamp)\r\n  CAST(REGEXP_SUBSTR(option_value, '[0-9]{10}') AS UNSIGNED) as time\r\nFROM ${prefix}options\r\nWHERE option_name = 'updraft_backup_history'\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Espacio Disponible para Contenido",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "Zabbix server" },
     "item": { "filter": "FS [/]: Space: Used, in %" },
     "itemTag": { "filter": "component: storage" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Tamaño de base de datos",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "wordpress",
     "rawSql": "SELECT \r\n  SUM(data_length + index_length) / 1024 / 1024 AS \"Tamaño (MB)\" \r\nFROM information_schema.TABLES \r\nWHERE table_schema = DATABASE()"
    }
   ]
  },
  {
   "title": "Tráfico web en vivo",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 13 },
   "targets": [
    {
     "dataset": "wordpress",
     "rawSql": "SELECT\r\n  time * 1000 as time,\r\n  count(uid) as \"Visitas\"\r\nFROM ${prefix}burst_statistics\r\nWHERE $__timeFilter(from_unixtime(time))\r\nGROUP BY time\r\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Total publicaciones",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "wordpress",
     "rawSql": "SELECT\r\n  post_type as \"Tipo\",\r\n  count(*) as \"Total\"\r\nFROM ${prefix}posts\r\nWHERE post_status = 'publish'\r\nAND post_type IN ('post', 'page') -- Solo contamos entradas y páginas\r\nGROUP BY post_type"
    }
   ]
  },
  {
   "title": "Amenazas bloqueadas",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 13 },
   "targets": [
    {
     "dimensions": { "WebACL": "WAF-alb" },
     "metricName": "BlockedRequests",
     "namespace": "AWS/WAFV2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  }
 ]
}