AWSTemplateFormatVersion: '2010-09-09'
Description: VPC con 3 Subredes Públicas (Ubuntu/Windows) y 3 Privadas conectadas a NAT Gateway - BIT + RDS MySQL Free Tier + Secrets Manager + S3

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Nombre del KeyPair para acceso SSH/RDP
    Default: vockey
  UbuntuAMI:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: /aws/service/canonical/ubuntu/server/24.04/stable/current/amd64/hvm/ebs-gp3/ami-id
  WindowsAMI:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: /aws/service/ami-windows-latest/Windows_Server-2025-English-Full-Base

Resources:
  # ========== VPC & Networking ========== #
  BITVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 192.5.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: BIT-VPC

  BITInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: BIT-InternetGateway

  BITGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref BITVPC
      InternetGatewayId: !Ref BITInternetGateway

  # --- Subredes Públicas ---
  BITPublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref BITVPC
      CidrBlock: 192.5.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: BIT-PublicSubnet1

  BITPublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref BITVPC
      CidrBlock: 192.5.4.0/24
      AvailabilityZone: !Select [1, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: BIT-PublicSubnet2

  BITPublicSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref BITVPC
      CidrBlock: 192.5.3.0/24
      AvailabilityZone: !Select [2, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: BIT-PublicSubnet3

  # --- Subredes Privadas ---
  BITPrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref BITVPC
      CidrBlock: 192.5.2.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: BIT-PrivateSubnet1

  BITPrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref BITVPC
      CidrBlock: 192.5.5.0/24
      AvailabilityZone: !Select [1, !GetAZs '']
      Tags:
        - Key: Name
          Value: BIT-PrivateSubnet2

  BITPrivateSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref BITVPC
      CidrBlock: 192.5.6.0/24
      AvailabilityZone: !Select [2, !GetAZs '']
      Tags:
        - Key: Name
          Value: BIT-PrivateSubnet3

  # --- NAT Gateway ---
  BITNATEIP:
    Type: AWS::EC2::EIP
    DependsOn: BITGatewayAttachment
    Properties:
      Domain: vpc

  BITNATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt BITNATEIP.AllocationId
      SubnetId: !Ref BITPublicSubnet1
      Tags:
        - Key: Name
          Value: BIT-NATGateway

  # --- Tablas de Rutas ---
  BITPublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref BITVPC
      Tags:
        - Key: Name
          Value: BIT-PublicRouteTable

  BITPublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref BITPublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref BITInternetGateway

  BITPrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref BITVPC
      Tags:
        - Key: Name
          Value: BIT-PrivateRouteTable

  BITPrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref BITPrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref BITNATGateway

  # --- Asociaciones de Rutas Públicas ---
  AssocPublic1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref BITPublicSubnet1
      RouteTableId: !Ref BITPublicRouteTable

  AssocPublic2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref BITPublicSubnet2
      RouteTableId: !Ref BITPublicRouteTable

  AssocPublic3:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref BITPublicSubnet3
      RouteTableId: !Ref BITPublicRouteTable

  # --- Asociaciones de Rutas Privadas ---
  AssocPrivate1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref BITPrivateSubnet1
      RouteTableId: !Ref BITPrivateRouteTable

  AssocPrivate2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref BITPrivateSubnet2
      RouteTableId: !Ref BITPrivateRouteTable

  AssocPrivate3:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref BITPrivateSubnet3
      RouteTableId: !Ref BITPrivateRouteTable

  # ========== Security Groups ========== #
  BITUbuntuSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Acceso HTTP/HTTPS y SSH para servidor Ubuntu con Nginx
      VpcId: !Ref BITVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: BIT-UbuntuSecurityGroup

  BITWindowsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Acceso RDP y SSH para servidor Windows
      VpcId: !Ref BITVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: BIT-WindowsSecurityGroup

  BITRDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Acceso MySQL exclusivamente por puerto 3306
      VpcId: !Ref BITVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref BITUbuntuSecurityGroup
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref BITWindowsSecurityGroup
      Tags:
        - Key: Name
          Value: BIT-RDSSecurityGroup

  # ========== INSTANCIAS ========== #
  UbuntuServerBIT:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref UbuntuAMI
      InstanceType: t3.micro
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !Ref BITPublicSubnet1
          GroupSet: [!Ref BITUbuntuSecurityGroup]
          AssociatePublicIpAddress: true
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e

          # Actualizar sistema
          apt update -y
          apt upgrade -y

          # Instalar Nginx, PHP-FPM y extensiones necesarias
          apt install -y nginx mysql-client git tree net-tools php-fpm php-mysql php-cli php-common php-gd php-curl php-mbstring php-xml php-zip php-soap php-intl php-bcmath

          # Crear directorio para WordPress
          mkdir -p /var/www/html/wordpress
          cd /var/www/html/wordpress

          # Descargar y extraer WordPress
          wget https://wordpress.org/latest.tar.gz
          tar xzvf latest.tar.gz --strip-components=1
          rm latest.tar.gz

          # Configurar permisos
          chown -R www-data:www-data /var/www/html/wordpress
          find /var/www/html/wordpress -type d -exec chmod 755 {} \;
          find /var/www/html/wordpress -type f -exec chmod 644 {} \;

          # Configurar Nginx server block para WordPress
          cat > /etc/nginx/sites-available/wordpress << 'EOFNGINX'
          server {
              listen 80 default_server;
              listen [::]:80 default_server;

              root /var/www/html/wordpress;
              index index.php index.html index.htm;

              server_name _;

              client_max_body_size 100M;

              location / {
                  try_files $uri $uri/ /index.php?$args;
              }

              location ~ \.php$ {
                  include snippets/fastcgi-php.conf;
                  fastcgi_pass unix:/run/php/php-fpm.sock;
                  fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                  include fastcgi_params;
              }

              location ~ /\.ht {
                  deny all;
              }

              location = /favicon.ico {
                  log_not_found off;
                  access_log off;
              }

              location = /robots.txt {
                  allow all;
                  log_not_found off;
                  access_log off;
              }

              location ~* \.(css|gif|ico|jpeg|jpg|js|png)$ {
                  expires max;
                  log_not_found off;
              }
          }
          EOFNGINX

          # Deshabilitar sitio por defecto y habilitar WordPress
          rm -f /etc/nginx/sites-enabled/default
          ln -sf /etc/nginx/sites-available/wordpress /etc/nginx/sites-enabled/

          # Verificar configuración de Nginx
          nginx -t

          # Reiniciar servicios (Ubuntu 24.04 usa PHP 8.1 por defecto)
          systemctl restart php8.3-fpm
          systemctl restart nginx

          # Habilitar servicios en el arranque
          systemctl enable nginx
          systemctl enable php8.3-fpm

          # Crear página de prueba
          echo "<html><body><h1>WordPress instalado correctamente</h1><p>Servidor: Ubuntu 24.04 + Nginx + PHP 8.1</p></body></html>" > /var/www/html/wordpress/test.html

          # Configuración de variables de entorno
          export TERM=xterm
          export SHELL=/bin/bash
      Tags:
        - Key: Name
          Value: Bastion-Ubuntu

  WindowsServerBIT:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref WindowsAMI
      InstanceType: t3.medium
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !Ref BITPublicSubnet3
          GroupSet: [!Ref BITWindowsSecurityGroup]
          AssociatePublicIpAddress: true
      Tags:
        - Key: Name
          Value: WS-2025

  # ========== RDS MySQL Free Tier con Secrets Manager ========== #
  BITDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Grupo de subredes privadas para RDS MySQL
      SubnetIds:
        - !Ref BITPrivateSubnet1
        - !Ref BITPrivateSubnet2
      Tags:
        - Key: Name
          Value: BIT-DBSubnetGroup

  BITRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: bit-rds-mysql
      DBInstanceClass: db.t3.micro
      Engine: mysql
      EngineVersion: '8.0.40'
      MasterUsername: admin
      ManageMasterUserPassword: true
      AllocatedStorage: 20
      StorageType: gp2
      DBSubnetGroupName: !Ref BITDBSubnetGroup
      VPCSecurityGroups:
        - !Ref BITRDSSecurityGroup
      MultiAZ: false
      PubliclyAccessible: false
      BackupRetentionPeriod: 7
      DeletionProtection: false
      Tags:
        - Key: Name
          Value: BIT-RDS-MySQL-FreeTier

  # ========== S3 Bucket Privado ========== #
  BITS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'bit-reto-bucket-${AWS::AccountId}-${AWS::Region}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Name
          Value: BIT-S3-Bucket

  BITS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref BITS3Bucket
      PolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Sid: PublicReadGetObject
          Effect: Allow
          Principal: '*'
          Action: 
            - s3:GetObject
          Resource: !Sub '${BITS3Bucket.Arn}/*'

Outputs:
  VPCId:
    Description: ID de la VPC principal del proyecto
    Value: !Ref BITVPC
    Export:
      Name: !Sub '${AWS::StackName}-VPCID'

  UbuntuPublicIP:
    Description: Direccion IP publica del servidor Ubuntu Bastion con Nginx
    Value: !GetAtt UbuntuServerBIT.PublicIp

  WindowsPublicIP:
    Description: Direccion IP publica del servidor Windows Server 2025
    Value: !GetAtt WindowsServerBIT.PublicIp

  RDSEndpoint:
    Description: Endpoint de conexion para RDS MySQL desde instancias EC2
    Value: !GetAtt BITRDSInstance.Endpoint.Address

  RDSPort:
    Description: Puerto de conexion para RDS MySQL
    Value: !GetAtt BITRDSInstance.Endpoint.Port

  RDSSecretArn:
    Description: ARN del secreto con credenciales de acceso a RDS MySQL
    Value: !GetAtt BITRDSInstance.MasterUserSecret.SecretArn

  S3BucketName:
    Description: Nombre del bucket S3 privado para almacenamiento
    Value: !Ref BITS3Bucket

  S3BucketArn:
    Description: ARN del bucket S3 privado
    Value: !GetAtt BITS3Bucket.Arn

  WordPressURL:
    Description: URL para acceder e instalar WordPress
    Value: !Sub 'http://${UbuntuServerBIT.PublicIp}'

  WordPressTestURL:
    Description: URL de la pagina de prueba
    Value: !Sub 'http://${UbuntuServerBIT.PublicIp}/test.html'

  UbuntuInstanceId:
    Description: Instance ID del servidor Ubuntu
    Value: !Ref UbuntuServerBIT

  WindowsInstanceId:
    Description: Instance ID del servidor Windows
    Value: !Ref WindowsServerBIT