{
 "title": "SERVER-METRICS",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "prefix",
    "query": "SELECT SUBSTRING_INDEX(table_name, 'users', 1) \nFROM information_schema.tables \nWHERE table_schema = DATABASE() \nAND table_name LIKE '%users' \nORDER BY LENGTH(table_name) ASC \nLIMIT 1;"
   }
  ]
 },
 "panels": [
  {
   "title": "Servidores activos",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "auto-scaling-Reto" },
     "metricName": "GroupTotalInstances",
     "namespace": "AWS/AutoScaling",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "WAF(cloudwatch-blocked)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "WebACL": "WAF-alb" },
     "metricName": "BlockedRequests",
     "namespace": "AWS/WAFV2",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Sum"
    },
    {
     "dimensions": { "WebACL": "WAF-alb" },
     "metricName": "AllowedRequests",
     "namespace": "AWS/WAFV2",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Memoria RAM",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "RDS Free-storage (cloudwatch)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "bit-rds-mysql" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Estres Base de datos",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Intentos de Bloqueo",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "wordpress",
     "rawSql": "SELECT\r\n  failed_login_ip as \"IP Bloqueada\",\r\n  count(*) as \"Intentos\",\r\n  max(lockdown_date) as \"Último Bloqueo\",\r\n  lock_reason as \"Motivo\"\r\nFROM wtsat_aiowps_login_lockdown\r\nGROUP BY failed_login_ip\r\nORDER BY count(*) DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "panel trafico",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "wordpress",
     "rawSql": "SELECT\r\n  page_url as \"Página Visitada\",\r\n  count(*) as \"Visitas (24h)\"\r\nFROM wtsat_burst_statistics\r\nWHERE time >= UNIX_TIMESTAMP(NOW() - INTERVAL 24 HOUR)\r\nGROUP BY page_url\r\nORDER BY count(*) DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Métricas de Sistema (Cloud watch)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "Zabbix server" },
     "item": { "filter": "nvme0n1: Disk utilization" },
     "itemTag": { "filter": "disk: nvme0n1" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "Zabbix server" },
     "item": { "filter": "Interface ens5: Bits received" },
     "itemTag": { "filter": "interface: ens5" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Rendimiento mysql (Cloudwatch)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "metricName": "ReadIOPS",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "metricName": "WriteIOPS",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}